name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x SKRoot-linuxKernelRoot/PermissionManager/gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Download dependencies
      run: ./gradlew dependencies --stacktrace

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: SKRoot-linuxKernelRoot/PermissionManager/app/build/outputs/apk/debug/*.apk

    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: SKRoot-linuxKernelRoot/PermissionManager/app/build/outputs/apk/release/*.apk
